basePath: /
definitions:
  error.errorResponse:
    properties:
      message:
        type: string
    type: object
  model.ResponseSignIn:
    properties:
      email:
        type: string
      token:
        type: string
    type: object
  model.ResponseSignUp:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  model.ResponseSuccess:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.SignInInput:
    properties:
      email:
        default: babdusalom72@gmail.com
        type: string
      password:
        default: "1996"
        type: string
    type: object
  model.User:
    properties:
      city:
        default: Navoi
        type: string
      email:
        default: babdusalom72@gmail.com
        type: string
      image:
        type: string
      password:
        default: "1996"
        type: string
      phone:
        default: +9989 99 331 96 12
        type: string
      username:
        default: MY
        type: string
    type: object
  model.UserUpdate:
    properties:
      city:
        default: Navoi
        type: string
      phone:
        default: +9989 99 331 96 12
        type: string
      username:
        default: MY
        type: string
    type: object
  model.VerificationCode:
    properties:
      code:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Mr Bobur
  description: API Server for MediumuZ Application
  title: MediumuZ API
  version: "2.0"
paths:
  /api/account/get-user:
    get:
      consumes:
      - application/json
      description: Get Account
      operationId: get-account
      parameters:
      - description: id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Account
      tags:
      - Profile
  /api/account/resend:
    get:
      consumes:
      - application/json
      description: resend code to email for  verification
      operationId: resend-code-email
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Resend cod for  Verification Email
      tags:
      - Profile
  /api/account/update:
    post:
      consumes:
      - application/json
      description: update profile
      operationId: update-profile
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: UpdateProfile
      tags:
      - Profile
  /api/account/upload-image:
    patch:
      consumes:
      - application/json
      - multipart/form-data
      description: Upload Account Image
      operationId: upload-image
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      - application/octet-stream
      - image/png
      - image/jpeg
      - image/jpg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload Account Image
      tags:
      - Profile
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login account
      operationId: login-account
      parameters:
      - description: accountin infor
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSignIn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: SignIn
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSignUp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: SignUp
      tags:
      - Auth
  /auth/verify:
    post:
      consumes:
      - application/json
      description: verify account
      operationId: verify-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.VerificationCode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Verify email
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
